<?php

namespace App\Http\Requests\backend;

use Illuminate\Foundation\Http\FormRequest;

class ChangePasswordRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'password_new' => 'required',
            'confirm_password' => 'required|same:password_new'
        ];
    }
    public function messages()
    {
        return [
            'password_new.required' => 'Vui lòng nhập mật khẩu mới',
            'confirm_password.required' => 'Vui lòng nhâp mật khẩu xác nhận',
            'confirm_password.same' => 'Mật khẩu xác nhận không đúng'
        ]; // TODO: Change the autogenerated stub

    }
}
